//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBankTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankInfoManagementEntities : DbContext
    {
        public BankInfoManagementEntities()
            : base("name=BankInfoManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditCardInfo> CreditCardInfo { get; set; }
        public virtual DbSet<DeposInfo> DeposInfo { get; set; }
        public virtual DbSet<EmploeeInfo> EmploeeInfo { get; set; }
        public virtual DbSet<RateInfo> RateInfo { get; set; }
        public virtual DbSet<OperationLog> OperationLog { get; set; }
        public virtual DbSet<TransferInfo> TransferInfo { get; set; }
    }
}
