//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBankTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeposInfo
    {
        public string CNo { get; set; }
        public string CName { get; set; }
        public string CSex { get; set; }
        public string CPassword { get; set; }
        public string CID { get; set; }
        public System.DateTime CDate { get; set; }
        public string CAdress { get; set; }
        public string CPhoneNum { get; set; }
    }
}
