//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBankTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploeeInfo
    {
        public string YNo { get; set; }
        public string YPassword { get; set; }
        public string YName { get; set; }
        public int YPosition { get; set; }
        public string YSex { get; set; }
        public string YPhoneNum { get; set; }
        public string YID { get; set; }
        public System.DateTime YWorkDate { get; set; }
        public Nullable<decimal> YWorkSalary { get; set; }
    }
}
