//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBankTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationLog
    {
        public string CNo { get; set; }
        public string CName { get; set; }
        public string CStyle { get; set; }
        public System.DateTime CDate { get; set; }
        public decimal CMoney { get; set; }
        public Nullable<int> CTimeLen { get; set; }
        public Nullable<double> CRate { get; set; }
        public Nullable<decimal> Interest { get; set; }
    }
}
