//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBankTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferInfo
    {
        public string OutNo { get; set; }
        public string OutName { get; set; }
        public string InNo { get; set; }
        public decimal TransMoney { get; set; }
        public System.DateTime TDate { get; set; }
    }
}
